name: CI

on:
  push:
    branches:
      - '*-dev'
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE.txt'
      - 'NOTICE'
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE.txt'
      - 'NOTICE'
  workflow_dispatch:
  workflow_call:

jobs:
  build-debug-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: actions/setup-java@v6
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
      - name: Build debug APK
        run: ./gradlew assembleLawnWithQuickstepGithubDebug
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: assembleLawnWithQuickstepGithubDebug
          path: build/outputs/apk/**/*.apk

  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: actions/setup-java@v6
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew spotlessCheck

  # Status check that is required in branch protection rules.
  final-status:
    needs:
      - build-debug-apk
      - check-style
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            echo "One or more required jobs failed"
            exit 1
          fi
          echo "All required jobs completed successfully."
